name: example
description: A package consuming code_generators

environment:
  sdk: '^3.3.0'

dev_dependencies:
  build_runner: ^2.4.9
  sqlitec:
    path: ../

dependencies:
  dart_style: ^2.3.6
  sqflite_common_ffi: ^2.3.3

