name: sqlitec
description: Automatically generate code for converting sqlite to dart.
repository: https://github.com/kmsbin/sqlitec
topics:
 - sqlite
 - build-runner
 - sqlc
 - codegen
environment:
  sdk: '^3.3.0'

version: 0.0.3

dependencies:
  build: ^4.0.0
  path: ^1.6.0
  source_gen: ^4.0.1
  glob: ^2.1.2
  sqlparser: ^0.41.2
  change_case: ^2.0.1
  dart_style: ^3.1.2
  collection: ^1.19.1
  code_builder: ^4.10.1
dev_dependencies:
  build_config: ^1.1.1
  build_runner: ^2.4.9
  flutter_lints: ^6.0.0
  pedantic: ^1.7.0
  test: ^1.5.0