name: sqlitec
description: Automatically generate code for converting sqlite to dart.
repository: https://github.com/kmsbin/sqlitec
topics:
 - sqlite
 - build-runner
 - sqlc
 - codegen
environment:
  sdk: '^3.3.0'

version: 0.0.2+2

dependencies:
  build: ^2.4.1
  path: ^1.6.0
  source_gen: ^1.5.0
  glob: ^2.1.2
  sqlparser: ^0.40.0
  change_case: ^2.0.1
  dart_style: ^2.3.6
  collection: ^1.19.1
  code_builder: ^4.10.1
dev_dependencies:
  build_config: ^1.1.1
  build_runner: ^2.4.9
  flutter_lints: ^4.0.0
  pedantic: ^1.7.0
  test: ^1.5.0